âœ“ WandB initialized in Online mode
Files already downloaded and verified
Files already downloaded and verified
The Iteration0:
================================
Epoch:0 and AverageLoss:2.3913875924961645
Epoch:1 and AverageLoss:1.6747069688099425
Epoch:2 and AverageLoss:1.4429503590859416
Epoch:3 and AverageLoss:1.31699110693334
Epoch:4 and AverageLoss:1.2009236626612865
Epoch:5 and AverageLoss:1.1113497194121866
Epoch:6 and AverageLoss:1.0283378210214094
Epoch:7 and AverageLoss:0.954844430889315
Epoch:8 and AverageLoss:0.901867656756545
Epoch:9 and AverageLoss:0.8425946747860336
Epoch:10 and AverageLoss:0.8025753214536115
Epoch:11 and AverageLoss:0.7543906627408684
Epoch:12 and AverageLoss:0.717542269498186
Epoch:13 and AverageLoss:0.680156274219913
Epoch:14 and AverageLoss:0.6433287438986551
Epoch:15 and AverageLoss:0.6067963458235611
Epoch:16 and AverageLoss:0.5712288012894828
Epoch:17 and AverageLoss:0.5455521773499297
Epoch:18 and AverageLoss:0.5137617849480466
Epoch:19 and AverageLoss:0.4864212253209575
Epoch:20 and AverageLoss:0.4639095552742024
Epoch:21 and AverageLoss:0.44109345709576325
Epoch:22 and AverageLoss:0.4152486899777142
Epoch:23 and AverageLoss:0.382886071072515
Epoch:24 and AverageLoss:0.35647397063424824
Forward Training Succesful
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week5/main.py", line 304, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week5/main.py", line 226, in main
    train_bool = training_using_ff_fb(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week5/main.py", line 99, in training_using_ff_fb
    feedback_training(net, trainloader, testloader, lr, momentum, save_dir,epochs,seed,device,batch_size)
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week5/back_train.py", line 63, in feedback_training
    testloss=recon_loss(net,testloader,batch_size,device,criterion)
                                                         ^^^^^^^^^
NameError: name 'criterion' is not defined
