âœ“ WandB initialized in Online mode
Files already downloaded and verified
Files already downloaded and verified
The Iteration0:
================================
Epoch:0 and AverageLoss:0.1823970173935756
Test Loss 0.09142315538623665
Epoch:1 and AverageLoss:0.07570901564548692
Test Loss 0.0640158692869959
Epoch:2 and AverageLoss:0.05712596898722222
Test Loss 0.05119327271852312
Epoch:3 and AverageLoss:0.047101834622185555
Test Loss 0.043365392739636986
Epoch:4 and AverageLoss:0.040613528379165306
Test Loss 0.038001981292721594
Epoch:5 and AverageLoss:0.03601192964521973
Test Loss 0.034074214652557916
Epoch:6 and AverageLoss:0.03256602298535045
Test Loss 0.03106482579266723
Epoch:7 and AverageLoss:0.02988330720235472
Test Loss 0.02867910954393918
Epoch:8 and AverageLoss:0.027723435269635353
Test Loss 0.02673439080296438
Epoch:9 and AverageLoss:0.025944052140235596
Test Loss 0.025113397808391835
Model Save Sucessfully
Training Sucessful
The Iteration1:
================================
Epoch:0 and AverageLoss:0.024480755776738573
Test Loss 0.023765406276606307
Epoch:1 and AverageLoss:0.02319575062550395
Test Loss 0.022572879573401018
Epoch:2 and AverageLoss:0.022076976049662855
Test Loss 0.021530540400668034
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week7/zp_study/main.py", line 225, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week7/zp_study/main.py", line 187, in main
    train_bool = training_using_reconstruction_and_predicitve_coding(net,save_dir, trainloader, testloader,config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week7/zp_study/main.py", line 101, in training_using_reconstruction_and_predicitve_coding
    recon_pc_training(net,trainloader,testloader,"train",config)
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week7/zp_study/recon_pc_train.py", line 53, in recon_pc_training
    running_loss.append(final_loss.item())
                        ^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7febfb1d36a0>
Traceback (most recent call last):
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 54, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 182, in teardown
    self._router.join()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
